console.log(
    String(3),
    String(true),
    String(false),
    String(null),
    String(undefined)
)
console.log(
    Number(null),
    Number(undefined)
)
console.log(
    Boolean(0),
    Boolean('0'),
    Boolean(""),
    Boolean('')
)